###First enpoint
POST http://localhost:8001/api/mutant HTTP/1.1
content-type:application/json

{
    "dna":["GTGCGA", "CGGTGC", "TTATGT", "AGATTG", "CTCCTA", "TCACTG"]
}

###Second enpoint

GET http://3.89.60.144:8001/mutant HTTP/1.1
content-type:application/json

