###First enpoint
POST http://54.175.116.27:3001/api/mutant HTTP/1.1
content-type:application/json

{
    "dna":["GTGCGA", "CGGTGC", "TTATGT", "AGATTG", "CTCCTA", "TCACTG"]
}

###Second enpoint

GET http://54.175.116.27:3001/api/stats HTTP/1.1
content-type:application/json

#####
POST http://localhost:3001/api/mutant HTTP/1.1
content-type:application/json

{
    "dna":["GTGCGA", "CGGTGC", "TTATGT", "AGATTG", "CTCCTA", "TCACTG"]
}

###Second enpoint


GET http://localhost:3001/api/stats HTTP/1.1
content-type:application/json


